name: All the Settings for cws
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Uses esLint and Prettier and checks the Code
    uses: ./.github/workflows/lint.yml
